from app_inv.admin.custom_user_admin import UserAdmin
from app_inv.admin.inventory_admin import inventory_admin
from app_inv.admin.catagory_admin import catagory_admin
from app_inv.admin.subscription_plan import SubscriptionPlan
from app_inv.admin.user_subscripotion import UserSubscription