# Generated by Django 5.2.7 on 2025-10-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inv.catagory'),
        ),
    ]
