# Generated by Django 5.2.7 on 2025-10-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0004_remove_user_catagory_user_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='catagory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, to='app_inv.catagory'),
        ),
    ]
