# Generated by Django 5.2.7 on 2025-10-06 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0005_remove_inventory_catagory_inventory_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catagories_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_fk', to='app_inv.catagory'),
        ),
    ]
