# Generated by Django 5.2.7 on 2025-10-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0006_catagory_user_alter_user_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
