# Generated by Django 5.2.7 on 2025-10-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0009_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
