# Generated by Django 5.2.7 on 2025-10-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0010_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='number_of_list',
        ),
        migrations.AddField(
            model_name='inventory',
            name='current_stock',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock',
            field=models.PositiveBigIntegerField(blank=True, default=5, null=True),
        ),
    ]
