# Generated by Django 5.2.7 on 2025-10-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0011_remove_inventory_number_of_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, choices=[('xxl', 'extra_extra_large'), ('xl', 'extra_large'), ('m', 'medium'), ('s', 'small')], default='xl', max_length=10, null=True),
        ),
    ]
