# Generated by Django 5.2.7 on 2025-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0013_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_catagoty',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_inventory',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
