# Generated by Django 5.2.7 on 2025-10-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inv', '0014_alter_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
    ]
